---
# tasks file for abcd
- include_tasks: installjava.yml
- include_tasks: group.yml
- include_tasks: user.yml
- include_tasks: download.yml
- include_tasks: extract.yml
- include_tasks: changegroup.yml
