---
- name: restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
  systemd:
   state: restarted
   daemon_reload: yes
  ignore_error: yes
- name: start tomcat
  service:
   name: tomcat
   state: started