---
- hosts: group1
  become: yes
  tasks:
  - name: uiinstall apache2
    service:
     name: apache2
     state: present
    ignore_errors: yes
  - name: install apache2
    apt:
     name: apache2
     state: present