---
- hosts: all
  become: yes
  tasks:
  - name: install apache22
    apt:
      name: "{{server1}}"
      state: present
  - name: start apache2
    service:
      name: "{{server1}}"
      state: started